services:
    php:
        image: php:8.3-apache
        container_name: tableau-stage-PHP
        ports:
            - "8004:80" # on définit le port pour accéder à l'application (localhost:8004) faire correspondre avec le PHPMyAdmin
        volumes:
            - ./src:/var/www/html # on monte le dossier courant dans le dossier /var/www/html du container
        build:
            context: .
            dockerfile: Dockerfile # correpond au nom du fichier
    db:
        image: mysql:8.0
        container_name: tableau_stage_php # identifier le nom du container sur docker
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tableau-stagee-php
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        ports:
            - "3309:3306"
    phpma:
        image: phpmyadmin/phpmyadmin
        container_name: tableau_stagePHP_phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
            UPLOAD_LIMIT: 20M
        ports:
            - "8084:80" # on définit le port pour accéder à phpmyadmin (localhost:8084) interface graphique pour visualiser la table
